# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/vladislavbushmakin/Desktop/qudi/gui/confocal/ui_confocalgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 1362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Options = QtWidgets.QMenu(self.menubar)
        self.menu_Options.setObjectName("menu_Options")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuToolbars = QtWidgets.QMenu(self.menuView)
        self.menuToolbars.setObjectName("menuToolbars")
        MainWindow.setMenuBar(self.menubar)
        self.depth_scan_dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.depth_scan_dockWidget.setObjectName("depth_scan_dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.depth_ViewWidget = ScanPlotWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_ViewWidget.sizePolicy().hasHeightForWidth())
        self.depth_ViewWidget.setSizePolicy(sizePolicy)
        self.depth_ViewWidget.setObjectName("depth_ViewWidget")
        self.horizontalLayout_5.addWidget(self.depth_ViewWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.depth_channel_ComboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.depth_channel_ComboBox.setObjectName("depth_channel_ComboBox")
        self.verticalLayout_2.addWidget(self.depth_channel_ComboBox)
        self.depth_cb_max_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_cb_max_DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.depth_cb_max_DoubleSpinBox.setSizePolicy(sizePolicy)
        self.depth_cb_max_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.depth_cb_max_DoubleSpinBox.setMouseTracking(True)
        self.depth_cb_max_DoubleSpinBox.setAcceptDrops(True)
        self.depth_cb_max_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depth_cb_max_DoubleSpinBox.setDecimals(2)
        self.depth_cb_max_DoubleSpinBox.setMinimum(-1000000000.0)
        self.depth_cb_max_DoubleSpinBox.setMaximum(1000000000.0)
        self.depth_cb_max_DoubleSpinBox.setProperty("value", 100000.0)
        self.depth_cb_max_DoubleSpinBox.setObjectName("depth_cb_max_DoubleSpinBox")
        self.verticalLayout_2.addWidget(self.depth_cb_max_DoubleSpinBox)
        self.depth_cb_high_percentile_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents)
        self.depth_cb_high_percentile_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.depth_cb_high_percentile_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depth_cb_high_percentile_DoubleSpinBox.setDecimals(2)
        self.depth_cb_high_percentile_DoubleSpinBox.setMinimum(0.0)
        self.depth_cb_high_percentile_DoubleSpinBox.setMaximum(100.0)
        self.depth_cb_high_percentile_DoubleSpinBox.setProperty("value", 100.0)
        self.depth_cb_high_percentile_DoubleSpinBox.setObjectName("depth_cb_high_percentile_DoubleSpinBox")
        self.verticalLayout_2.addWidget(self.depth_cb_high_percentile_DoubleSpinBox)
        self.depth_cb_ViewWidget = PlotWidget(self.dockWidgetContents)
        self.depth_cb_ViewWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.depth_cb_ViewWidget.setObjectName("depth_cb_ViewWidget")
        self.verticalLayout_2.addWidget(self.depth_cb_ViewWidget)
        self.depth_cb_low_percentile_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents)
        self.depth_cb_low_percentile_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.depth_cb_low_percentile_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depth_cb_low_percentile_DoubleSpinBox.setDecimals(2)
        self.depth_cb_low_percentile_DoubleSpinBox.setMinimum(0.0)
        self.depth_cb_low_percentile_DoubleSpinBox.setMaximum(100.0)
        self.depth_cb_low_percentile_DoubleSpinBox.setProperty("value", 0.0)
        self.depth_cb_low_percentile_DoubleSpinBox.setObjectName("depth_cb_low_percentile_DoubleSpinBox")
        self.verticalLayout_2.addWidget(self.depth_cb_low_percentile_DoubleSpinBox)
        self.depth_cb_min_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_cb_min_DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.depth_cb_min_DoubleSpinBox.setSizePolicy(sizePolicy)
        self.depth_cb_min_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.depth_cb_min_DoubleSpinBox.setMouseTracking(True)
        self.depth_cb_min_DoubleSpinBox.setAcceptDrops(True)
        self.depth_cb_min_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depth_cb_min_DoubleSpinBox.setAccelerated(True)
        self.depth_cb_min_DoubleSpinBox.setDecimals(2)
        self.depth_cb_min_DoubleSpinBox.setMinimum(-1000000000.0)
        self.depth_cb_min_DoubleSpinBox.setMaximum(1000000000.0)
        self.depth_cb_min_DoubleSpinBox.setProperty("value", 1000.0)
        self.depth_cb_min_DoubleSpinBox.setObjectName("depth_cb_min_DoubleSpinBox")
        self.verticalLayout_2.addWidget(self.depth_cb_min_DoubleSpinBox)
        self.depth_cb_centiles_RadioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.depth_cb_centiles_RadioButton.setChecked(True)
        self.depth_cb_centiles_RadioButton.setObjectName("depth_cb_centiles_RadioButton")
        self.verticalLayout_2.addWidget(self.depth_cb_centiles_RadioButton)
        self.depth_cb_manual_RadioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.depth_cb_manual_RadioButton.setChecked(False)
        self.depth_cb_manual_RadioButton.setObjectName("depth_cb_manual_RadioButton")
        self.verticalLayout_2.addWidget(self.depth_cb_manual_RadioButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.depth_scan_dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.depth_scan_dockWidget)
        self.optimizer_dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.optimizer_dockWidget.setObjectName("optimizer_dockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.xy_refocus_ViewWidget_2 = ScanPlotWidget(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.xy_refocus_ViewWidget_2.sizePolicy().hasHeightForWidth())
        self.xy_refocus_ViewWidget_2.setSizePolicy(sizePolicy)
        self.xy_refocus_ViewWidget_2.setMinimumSize(QtCore.QSize(220, 220))
        self.xy_refocus_ViewWidget_2.setMaximumSize(QtCore.QSize(220, 220))
        self.xy_refocus_ViewWidget_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.xy_refocus_ViewWidget_2.setBaseSize(QtCore.QSize(0, 0))
        self.xy_refocus_ViewWidget_2.setObjectName("xy_refocus_ViewWidget_2")
        self.horizontalLayout_12.addWidget(self.xy_refocus_ViewWidget_2)
        self.depth_refocus_ViewWidget_2 = PlotWidget(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_refocus_ViewWidget_2.sizePolicy().hasHeightForWidth())
        self.depth_refocus_ViewWidget_2.setSizePolicy(sizePolicy)
        self.depth_refocus_ViewWidget_2.setMinimumSize(QtCore.QSize(0, 220))
        self.depth_refocus_ViewWidget_2.setObjectName("depth_refocus_ViewWidget_2")
        self.horizontalLayout_12.addWidget(self.depth_refocus_ViewWidget_2)
        self.horizontalLayout_12.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.refocus_position_label = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.refocus_position_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.refocus_position_label.setObjectName("refocus_position_label")
        self.horizontalLayout_13.addWidget(self.refocus_position_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.optimizer_dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.optimizer_dockWidget)
        self.scan_control_dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.scan_control_dockWidget.setMaximumSize(QtCore.QSize(524287, 170))
        self.scan_control_dockWidget.setObjectName("scan_control_dockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.resolutionLabel = QtWidgets.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolutionLabel.sizePolicy().hasHeightForWidth())
        self.resolutionLabel.setSizePolicy(sizePolicy)
        self.resolutionLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.resolutionLabel.setMaximumSize(QtCore.QSize(125, 16777215))
        self.resolutionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.gridLayout_3.addWidget(self.resolutionLabel, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.dockWidgetContents_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 2, 1, 1)
        self.scanrangeLabel = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.scanrangeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scanrangeLabel.setObjectName("scanrangeLabel")
        self.gridLayout_3.addWidget(self.scanrangeLabel, 0, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(733, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 5, 1, 1)
        self.xAxisLabel = QtWidgets.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xAxisLabel.sizePolicy().hasHeightForWidth())
        self.xAxisLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.xAxisLabel.setFont(font)
        self.xAxisLabel.setScaledContents(False)
        self.xAxisLabel.setObjectName("xAxisLabel")
        self.gridLayout_3.addWidget(self.xAxisLabel, 1, 0, 1, 1)
        self.xy_res_InputWidget = QtWidgets.QSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_res_InputWidget.sizePolicy().hasHeightForWidth())
        self.xy_res_InputWidget.setSizePolicy(sizePolicy)
        self.xy_res_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.xy_res_InputWidget.setMouseTracking(True)
        self.xy_res_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.xy_res_InputWidget.setAcceptDrops(True)
        self.xy_res_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_res_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.xy_res_InputWidget.setAccelerated(True)
        self.xy_res_InputWidget.setMinimum(2)
        self.xy_res_InputWidget.setMaximum(10000)
        self.xy_res_InputWidget.setProperty("value", 100)
        self.xy_res_InputWidget.setObjectName("xy_res_InputWidget")
        self.gridLayout_3.addWidget(self.xy_res_InputWidget, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 2, 1, 1)
        self.x_max_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.x_max_InputWidget.setSizePolicy(sizePolicy)
        self.x_max_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.x_max_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_max_InputWidget.setMouseTracking(True)
        self.x_max_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.x_max_InputWidget.setAcceptDrops(True)
        self.x_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_max_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.x_max_InputWidget.setAccelerated(True)
        self.x_max_InputWidget.setDecimals(2)
        self.x_max_InputWidget.setMinimum(-200.0)
        self.x_max_InputWidget.setMaximum(200.0)
        self.x_max_InputWidget.setObjectName("x_max_InputWidget")
        self.gridLayout_3.addWidget(self.x_max_InputWidget, 1, 4, 1, 1)
        self.x_SliderWidget = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.x_SliderWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.x_SliderWidget.setSingleStep(1)
        self.x_SliderWidget.setOrientation(QtCore.Qt.Horizontal)
        self.x_SliderWidget.setObjectName("x_SliderWidget")
        self.gridLayout_3.addWidget(self.x_SliderWidget, 1, 5, 1, 1)
        self.x_current_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_current_InputWidget.sizePolicy().hasHeightForWidth())
        self.x_current_InputWidget.setSizePolicy(sizePolicy)
        self.x_current_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.x_current_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_current_InputWidget.setMouseTracking(True)
        self.x_current_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.x_current_InputWidget.setAcceptDrops(True)
        self.x_current_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_current_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.x_current_InputWidget.setAccelerated(True)
        self.x_current_InputWidget.setDecimals(2)
        self.x_current_InputWidget.setMinimum(-1000.0)
        self.x_current_InputWidget.setMaximum(1000.0)
        self.x_current_InputWidget.setSingleStep(0.01)
        self.x_current_InputWidget.setObjectName("x_current_InputWidget")
        self.gridLayout_3.addWidget(self.x_current_InputWidget, 1, 6, 1, 1)
        self.yAxisLabel = QtWidgets.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yAxisLabel.sizePolicy().hasHeightForWidth())
        self.yAxisLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yAxisLabel.setFont(font)
        self.yAxisLabel.setObjectName("yAxisLabel")
        self.gridLayout_3.addWidget(self.yAxisLabel, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.dockWidgetContents_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 2, 2, 1, 1)
        self.y_min_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.y_min_InputWidget.setSizePolicy(sizePolicy)
        self.y_min_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.y_min_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_min_InputWidget.setMouseTracking(True)
        self.y_min_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.y_min_InputWidget.setAcceptDrops(True)
        self.y_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_min_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.y_min_InputWidget.setAccelerated(True)
        self.y_min_InputWidget.setDecimals(2)
        self.y_min_InputWidget.setMinimum(-200.0)
        self.y_min_InputWidget.setMaximum(200.0)
        self.y_min_InputWidget.setObjectName("y_min_InputWidget")
        self.gridLayout_3.addWidget(self.y_min_InputWidget, 2, 3, 1, 1)
        self.y_max_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.y_max_InputWidget.setSizePolicy(sizePolicy)
        self.y_max_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.y_max_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_max_InputWidget.setMouseTracking(True)
        self.y_max_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.y_max_InputWidget.setAcceptDrops(True)
        self.y_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_max_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.y_max_InputWidget.setAccelerated(True)
        self.y_max_InputWidget.setDecimals(2)
        self.y_max_InputWidget.setMinimum(-200.0)
        self.y_max_InputWidget.setMaximum(200.0)
        self.y_max_InputWidget.setObjectName("y_max_InputWidget")
        self.gridLayout_3.addWidget(self.y_max_InputWidget, 2, 4, 1, 1)
        self.y_SliderWidget = QtWidgets.QSlider(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_SliderWidget.sizePolicy().hasHeightForWidth())
        self.y_SliderWidget.setSizePolicy(sizePolicy)
        self.y_SliderWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.y_SliderWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.y_SliderWidget.setBaseSize(QtCore.QSize(0, 0))
        self.y_SliderWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.y_SliderWidget.setOrientation(QtCore.Qt.Horizontal)
        self.y_SliderWidget.setObjectName("y_SliderWidget")
        self.gridLayout_3.addWidget(self.y_SliderWidget, 2, 5, 1, 1)
        self.y_current_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_current_InputWidget.sizePolicy().hasHeightForWidth())
        self.y_current_InputWidget.setSizePolicy(sizePolicy)
        self.y_current_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.y_current_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_current_InputWidget.setMouseTracking(True)
        self.y_current_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.y_current_InputWidget.setAcceptDrops(True)
        self.y_current_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_current_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.y_current_InputWidget.setAccelerated(True)
        self.y_current_InputWidget.setDecimals(2)
        self.y_current_InputWidget.setMinimum(-1000.0)
        self.y_current_InputWidget.setMaximum(1000.0)
        self.y_current_InputWidget.setSingleStep(0.01)
        self.y_current_InputWidget.setObjectName("y_current_InputWidget")
        self.gridLayout_3.addWidget(self.y_current_InputWidget, 2, 6, 1, 1)
        self.zAxisLabel = QtWidgets.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zAxisLabel.sizePolicy().hasHeightForWidth())
        self.zAxisLabel.setSizePolicy(sizePolicy)
        self.zAxisLabel.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.zAxisLabel.setFont(font)
        self.zAxisLabel.setObjectName("zAxisLabel")
        self.gridLayout_3.addWidget(self.zAxisLabel, 3, 0, 1, 1)
        self.z_res_InputWidget = QtWidgets.QSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_res_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_res_InputWidget.setSizePolicy(sizePolicy)
        self.z_res_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_res_InputWidget.setMouseTracking(True)
        self.z_res_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_res_InputWidget.setAcceptDrops(True)
        self.z_res_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_res_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.z_res_InputWidget.setAccelerated(True)
        self.z_res_InputWidget.setMinimum(2)
        self.z_res_InputWidget.setMaximum(10000)
        self.z_res_InputWidget.setProperty("value", 100)
        self.z_res_InputWidget.setObjectName("z_res_InputWidget")
        self.gridLayout_3.addWidget(self.z_res_InputWidget, 3, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.dockWidgetContents_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 3, 2, 1, 1)
        self.z_min_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_min_InputWidget.setSizePolicy(sizePolicy)
        self.z_min_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.z_min_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_min_InputWidget.setMouseTracking(True)
        self.z_min_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_min_InputWidget.setAcceptDrops(True)
        self.z_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_min_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.z_min_InputWidget.setAccelerated(True)
        self.z_min_InputWidget.setDecimals(2)
        self.z_min_InputWidget.setMinimum(-200.0)
        self.z_min_InputWidget.setMaximum(200.0)
        self.z_min_InputWidget.setObjectName("z_min_InputWidget")
        self.gridLayout_3.addWidget(self.z_min_InputWidget, 3, 3, 1, 1)
        self.z_max_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_max_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_max_InputWidget.setSizePolicy(sizePolicy)
        self.z_max_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.z_max_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_max_InputWidget.setMouseTracking(True)
        self.z_max_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_max_InputWidget.setAcceptDrops(True)
        self.z_max_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_max_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.z_max_InputWidget.setAccelerated(True)
        self.z_max_InputWidget.setDecimals(2)
        self.z_max_InputWidget.setMinimum(-200.0)
        self.z_max_InputWidget.setMaximum(200.0)
        self.z_max_InputWidget.setObjectName("z_max_InputWidget")
        self.gridLayout_3.addWidget(self.z_max_InputWidget, 3, 4, 1, 1)
        self.z_SliderWidget = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.z_SliderWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.z_SliderWidget.setOrientation(QtCore.Qt.Horizontal)
        self.z_SliderWidget.setObjectName("z_SliderWidget")
        self.gridLayout_3.addWidget(self.z_SliderWidget, 3, 5, 1, 1)
        self.z_current_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_current_InputWidget.sizePolicy().hasHeightForWidth())
        self.z_current_InputWidget.setSizePolicy(sizePolicy)
        self.z_current_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.z_current_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.z_current_InputWidget.setMouseTracking(True)
        self.z_current_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.z_current_InputWidget.setAcceptDrops(True)
        self.z_current_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_current_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.z_current_InputWidget.setDecimals(2)
        self.z_current_InputWidget.setMinimum(-1000.0)
        self.z_current_InputWidget.setMaximum(1000.0)
        self.z_current_InputWidget.setSingleStep(0.01)
        self.z_current_InputWidget.setObjectName("z_current_InputWidget")
        self.gridLayout_3.addWidget(self.z_current_InputWidget, 3, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 4, 5, 1, 1)
        self.x_min_InputWidget = ScienDSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_min_InputWidget.sizePolicy().hasHeightForWidth())
        self.x_min_InputWidget.setSizePolicy(sizePolicy)
        self.x_min_InputWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.x_min_InputWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_min_InputWidget.setMouseTracking(True)
        self.x_min_InputWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.x_min_InputWidget.setAcceptDrops(True)
        self.x_min_InputWidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_min_InputWidget.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.x_min_InputWidget.setAccelerated(True)
        self.x_min_InputWidget.setDecimals(2)
        self.x_min_InputWidget.setMinimum(-200.0)
        self.x_min_InputWidget.setMaximum(200.0)
        self.x_min_InputWidget.setSingleStep(0.1)
        self.x_min_InputWidget.setObjectName("x_min_InputWidget")
        self.gridLayout_3.addWidget(self.x_min_InputWidget, 1, 3, 1, 1)
        self.scan_control_dockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.scan_control_dockWidget)
        self.xy_scan_dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.xy_scan_dockWidget.setObjectName("xy_scan_dockWidget")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.xy_ViewWidget = ScanPlotWidget(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_ViewWidget.sizePolicy().hasHeightForWidth())
        self.xy_ViewWidget.setSizePolicy(sizePolicy)
        self.xy_ViewWidget.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.xy_ViewWidget.setObjectName("xy_ViewWidget")
        self.horizontalLayout_4.addWidget(self.xy_ViewWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.xy_channel_ComboBox = QtWidgets.QComboBox(self.dockWidgetContents_4)
        self.xy_channel_ComboBox.setObjectName("xy_channel_ComboBox")
        self.verticalLayout.addWidget(self.xy_channel_ComboBox)
        self.xy_cb_max_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_cb_max_DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.xy_cb_max_DoubleSpinBox.setSizePolicy(sizePolicy)
        self.xy_cb_max_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xy_cb_max_DoubleSpinBox.setMouseTracking(True)
        self.xy_cb_max_DoubleSpinBox.setAcceptDrops(True)
        self.xy_cb_max_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_cb_max_DoubleSpinBox.setAccelerated(True)
        self.xy_cb_max_DoubleSpinBox.setDecimals(2)
        self.xy_cb_max_DoubleSpinBox.setMinimum(-1000000000.0)
        self.xy_cb_max_DoubleSpinBox.setMaximum(1000000000.0)
        self.xy_cb_max_DoubleSpinBox.setProperty("value", 100000.0)
        self.xy_cb_max_DoubleSpinBox.setObjectName("xy_cb_max_DoubleSpinBox")
        self.verticalLayout.addWidget(self.xy_cb_max_DoubleSpinBox)
        self.xy_cb_high_percentile_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents_4)
        self.xy_cb_high_percentile_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xy_cb_high_percentile_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_cb_high_percentile_DoubleSpinBox.setDecimals(2)
        self.xy_cb_high_percentile_DoubleSpinBox.setMinimum(0.0)
        self.xy_cb_high_percentile_DoubleSpinBox.setMaximum(100.0)
        self.xy_cb_high_percentile_DoubleSpinBox.setProperty("value", 100.0)
        self.xy_cb_high_percentile_DoubleSpinBox.setObjectName("xy_cb_high_percentile_DoubleSpinBox")
        self.verticalLayout.addWidget(self.xy_cb_high_percentile_DoubleSpinBox)
        self.xy_cb_ViewWidget = PlotWidget(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_cb_ViewWidget.sizePolicy().hasHeightForWidth())
        self.xy_cb_ViewWidget.setSizePolicy(sizePolicy)
        self.xy_cb_ViewWidget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.xy_cb_ViewWidget.setObjectName("xy_cb_ViewWidget")
        self.verticalLayout.addWidget(self.xy_cb_ViewWidget)
        self.xy_cb_low_percentile_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents_4)
        self.xy_cb_low_percentile_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xy_cb_low_percentile_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_cb_low_percentile_DoubleSpinBox.setDecimals(2)
        self.xy_cb_low_percentile_DoubleSpinBox.setMinimum(0.0)
        self.xy_cb_low_percentile_DoubleSpinBox.setMaximum(100.0)
        self.xy_cb_low_percentile_DoubleSpinBox.setProperty("value", 0.0)
        self.xy_cb_low_percentile_DoubleSpinBox.setObjectName("xy_cb_low_percentile_DoubleSpinBox")
        self.verticalLayout.addWidget(self.xy_cb_low_percentile_DoubleSpinBox)
        self.xy_cb_min_DoubleSpinBox = ScienDSpinBox(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_cb_min_DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.xy_cb_min_DoubleSpinBox.setSizePolicy(sizePolicy)
        self.xy_cb_min_DoubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xy_cb_min_DoubleSpinBox.setMouseTracking(True)
        self.xy_cb_min_DoubleSpinBox.setAcceptDrops(True)
        self.xy_cb_min_DoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xy_cb_min_DoubleSpinBox.setAccelerated(True)
        self.xy_cb_min_DoubleSpinBox.setDecimals(2)
        self.xy_cb_min_DoubleSpinBox.setMinimum(-1000000000.0)
        self.xy_cb_min_DoubleSpinBox.setMaximum(10000000.0)
        self.xy_cb_min_DoubleSpinBox.setProperty("value", 1000.0)
        self.xy_cb_min_DoubleSpinBox.setObjectName("xy_cb_min_DoubleSpinBox")
        self.verticalLayout.addWidget(self.xy_cb_min_DoubleSpinBox)
        self.xy_cb_centiles_RadioButton = QtWidgets.QRadioButton(self.dockWidgetContents_4)
        self.xy_cb_centiles_RadioButton.setChecked(True)
        self.xy_cb_centiles_RadioButton.setObjectName("xy_cb_centiles_RadioButton")
        self.verticalLayout.addWidget(self.xy_cb_centiles_RadioButton)
        self.xy_cb_manual_RadioButton = QtWidgets.QRadioButton(self.dockWidgetContents_4)
        self.xy_cb_manual_RadioButton.setChecked(False)
        self.xy_cb_manual_RadioButton.setObjectName("xy_cb_manual_RadioButton")
        self.verticalLayout.addWidget(self.xy_cb_manual_RadioButton)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.xy_scan_dockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.xy_scan_dockWidget)
        self.scan_ToolBar = QtWidgets.QToolBar(MainWindow)
        self.scan_ToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.scan_ToolBar.setObjectName("scan_ToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.scan_ToolBar)
        self.util_ToolBar = QtWidgets.QToolBar(MainWindow)
        self.util_ToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.util_ToolBar.setObjectName("util_ToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.util_ToolBar)
        self.tilt_correction_dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.tilt_correction_dockWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilt_correction_dockWidget.sizePolicy().hasHeightForWidth())
        self.tilt_correction_dockWidget.setSizePolicy(sizePolicy)
        self.tilt_correction_dockWidget.setMaximumSize(QtCore.QSize(300, 524287))
        self.tilt_correction_dockWidget.setObjectName("tilt_correction_dockWidget")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.calc_tilt_pushButton = QtWidgets.QPushButton(self.dockWidgetContents_6)
        self.calc_tilt_pushButton.setObjectName("calc_tilt_pushButton")
        self.gridLayout.addWidget(self.calc_tilt_pushButton, 4, 0, 1, 2)
        self.tilt_set_02_pushButton = QtWidgets.QPushButton(self.dockWidgetContents_6)
        self.tilt_set_02_pushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tilt_set_02_pushButton.setObjectName("tilt_set_02_pushButton")
        self.gridLayout.addWidget(self.tilt_set_02_pushButton, 2, 0, 1, 1)
        self.tilt_set_03_pushButton = QtWidgets.QPushButton(self.dockWidgetContents_6)
        self.tilt_set_03_pushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tilt_set_03_pushButton.setObjectName("tilt_set_03_pushButton")
        self.gridLayout.addWidget(self.tilt_set_03_pushButton, 3, 0, 1, 1)
        self.tilt_01_x_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_01_x_pos_doubleSpinBox.setEnabled(True)
        self.tilt_01_x_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_01_x_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_01_x_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_01_x_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_01_x_pos_doubleSpinBox.setDecimals(2)
        self.tilt_01_x_pos_doubleSpinBox.setMaximum(200.0)
        self.tilt_01_x_pos_doubleSpinBox.setObjectName("tilt_01_x_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_01_x_pos_doubleSpinBox, 1, 1, 1, 1)
        self.tilt_set_01_pushButton = QtWidgets.QPushButton(self.dockWidgetContents_6)
        self.tilt_set_01_pushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tilt_set_01_pushButton.setObjectName("tilt_set_01_pushButton")
        self.gridLayout.addWidget(self.tilt_set_01_pushButton, 1, 0, 1, 1)
        self.tiltpoint_label = QtWidgets.QLabel(self.dockWidgetContents_6)
        self.tiltpoint_label.setObjectName("tiltpoint_label")
        self.gridLayout.addWidget(self.tiltpoint_label, 0, 0, 1, 1)
        self.tilt_01_y_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_01_y_pos_doubleSpinBox.setEnabled(True)
        self.tilt_01_y_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_01_y_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_01_y_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_01_y_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_01_y_pos_doubleSpinBox.setDecimals(2)
        self.tilt_01_y_pos_doubleSpinBox.setMaximum(200.0)
        self.tilt_01_y_pos_doubleSpinBox.setObjectName("tilt_01_y_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_01_y_pos_doubleSpinBox, 1, 2, 1, 1)
        self.tilt_x_label = QtWidgets.QLabel(self.dockWidgetContents_6)
        self.tilt_x_label.setObjectName("tilt_x_label")
        self.gridLayout.addWidget(self.tilt_x_label, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.tilt_02_x_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_02_x_pos_doubleSpinBox.setEnabled(True)
        self.tilt_02_x_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_02_x_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_02_x_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_02_x_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_02_x_pos_doubleSpinBox.setDecimals(2)
        self.tilt_02_x_pos_doubleSpinBox.setMaximum(200.0)
        self.tilt_02_x_pos_doubleSpinBox.setObjectName("tilt_02_x_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_02_x_pos_doubleSpinBox, 2, 1, 1, 1)
        self.tilt_03_z_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_03_z_pos_doubleSpinBox.setEnabled(True)
        self.tilt_03_z_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_03_z_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_03_z_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_03_z_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_03_z_pos_doubleSpinBox.setDecimals(2)
        self.tilt_03_z_pos_doubleSpinBox.setMinimum(-100.0)
        self.tilt_03_z_pos_doubleSpinBox.setMaximum(100.0)
        self.tilt_03_z_pos_doubleSpinBox.setObjectName("tilt_03_z_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_03_z_pos_doubleSpinBox, 3, 3, 1, 1)
        self.tilt_01_z_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_01_z_pos_doubleSpinBox.setEnabled(True)
        self.tilt_01_z_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_01_z_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_01_z_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_01_z_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_01_z_pos_doubleSpinBox.setDecimals(2)
        self.tilt_01_z_pos_doubleSpinBox.setMinimum(-100.0)
        self.tilt_01_z_pos_doubleSpinBox.setMaximum(100.0)
        self.tilt_01_z_pos_doubleSpinBox.setObjectName("tilt_01_z_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_01_z_pos_doubleSpinBox, 1, 3, 1, 1)
        self.tilt_03_x_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_03_x_pos_doubleSpinBox.setEnabled(True)
        self.tilt_03_x_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_03_x_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_03_x_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_03_x_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_03_x_pos_doubleSpinBox.setDecimals(2)
        self.tilt_03_x_pos_doubleSpinBox.setMaximum(200.0)
        self.tilt_03_x_pos_doubleSpinBox.setObjectName("tilt_03_x_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_03_x_pos_doubleSpinBox, 3, 1, 1, 1)
        self.tilt_03_y_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_03_y_pos_doubleSpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilt_03_y_pos_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.tilt_03_y_pos_doubleSpinBox.setSizePolicy(sizePolicy)
        self.tilt_03_y_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_03_y_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_03_y_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_03_y_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_03_y_pos_doubleSpinBox.setDecimals(2)
        self.tilt_03_y_pos_doubleSpinBox.setMaximum(200.0)
        self.tilt_03_y_pos_doubleSpinBox.setObjectName("tilt_03_y_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_03_y_pos_doubleSpinBox, 3, 2, 1, 1)
        self.tilt_02_z_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_02_z_pos_doubleSpinBox.setEnabled(True)
        self.tilt_02_z_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_02_z_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_02_z_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_02_z_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_02_z_pos_doubleSpinBox.setDecimals(2)
        self.tilt_02_z_pos_doubleSpinBox.setMinimum(-100.0)
        self.tilt_02_z_pos_doubleSpinBox.setMaximum(100.0)
        self.tilt_02_z_pos_doubleSpinBox.setObjectName("tilt_02_z_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_02_z_pos_doubleSpinBox, 2, 3, 1, 1)
        self.tilt_02_y_pos_doubleSpinBox = ScienDSpinBox(self.dockWidgetContents_6)
        self.tilt_02_y_pos_doubleSpinBox.setEnabled(True)
        self.tilt_02_y_pos_doubleSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tilt_02_y_pos_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tilt_02_y_pos_doubleSpinBox.setReadOnly(True)
        self.tilt_02_y_pos_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tilt_02_y_pos_doubleSpinBox.setDecimals(2)
        self.tilt_02_y_pos_doubleSpinBox.setMaximum(200.0)
        self.tilt_02_y_pos_doubleSpinBox.setObjectName("tilt_02_y_pos_doubleSpinBox")
        self.gridLayout.addWidget(self.tilt_02_y_pos_doubleSpinBox, 2, 2, 1, 1)
        self.tilt_y_label = QtWidgets.QLabel(self.dockWidgetContents_6)
        self.tilt_y_label.setObjectName("tilt_y_label")
        self.gridLayout.addWidget(self.tilt_y_label, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.tilt_z_label = QtWidgets.QLabel(self.dockWidgetContents_6)
        self.tilt_z_label.setObjectName("tilt_z_label")
        self.gridLayout.addWidget(self.tilt_z_label, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tilt_correction_dockWidget.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.tilt_correction_dockWidget)
        self.historyToolBar = QtWidgets.QToolBar(MainWindow)
        self.historyToolBar.setEnabled(True)
        self.historyToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.historyToolBar.setObjectName("historyToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.historyToolBar)
        self.scanLineDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.scanLineDockWidget.setObjectName("scanLineDockWidget")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scanLineGraphicsView = PlotWidget(self.dockWidgetContents_5)
        self.scanLineGraphicsView.setObjectName("scanLineGraphicsView")
        self.gridLayout_4.addWidget(self.scanLineGraphicsView, 0, 0, 1, 1)
        self.scanLineDockWidget.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.scanLineDockWidget)
        self.limitsToolBar = QtWidgets.QToolBar(MainWindow)
        self.limitsToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.limitsToolBar.setObjectName("limitsToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.limitsToolBar)
        self.actionSave_XY_Scan = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_XY_Scan.setIcon(icon)
        self.actionSave_XY_Scan.setObjectName("actionSave_XY_Scan")
        self.actionSave_configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_configuration.setIcon(icon)
        self.actionSave_configuration.setObjectName("actionSave_configuration")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Settings.setIcon(icon1)
        self.action_Settings.setObjectName("action_Settings")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionClose.setObjectName("actionClose")
        self.actionSave_Depth_Scan = QtWidgets.QAction(MainWindow)
        self.actionSave_Depth_Scan.setIcon(icon)
        self.actionSave_Depth_Scan.setObjectName("actionSave_Depth_Scan")
        self.action_optimizer_settings = QtWidgets.QAction(MainWindow)
        self.action_optimizer_settings.setIcon(icon1)
        self.action_optimizer_settings.setObjectName("action_optimizer_settings")
        self.action_zoom = QtWidgets.QAction(MainWindow)
        self.action_zoom.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/zoom-select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/32x32/search_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_zoom.setIcon(icon3)
        self.action_zoom.setObjectName("action_zoom")
        self.actionXY_scan_view = QtWidgets.QAction(MainWindow)
        self.actionXY_scan_view.setCheckable(True)
        self.actionXY_scan_view.setChecked(True)
        self.actionXY_scan_view.setObjectName("actionXY_scan_view")
        self.actionDepth_scan_view = QtWidgets.QAction(MainWindow)
        self.actionDepth_scan_view.setCheckable(True)
        self.actionDepth_scan_view.setChecked(True)
        self.actionDepth_scan_view.setObjectName("actionDepth_scan_view")
        self.actionScan_control_view = QtWidgets.QAction(MainWindow)
        self.actionScan_control_view.setCheckable(True)
        self.actionScan_control_view.setChecked(True)
        self.actionScan_control_view.setObjectName("actionScan_control_view")
        self.actionOptimizer_view = QtWidgets.QAction(MainWindow)
        self.actionOptimizer_view.setCheckable(True)
        self.actionOptimizer_view.setChecked(True)
        self.actionOptimizer_view.setObjectName("actionOptimizer_view")
        self.action_scan_xy_start = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/22x22/scan-xy-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_scan_xy_start.setIcon(icon4)
        self.action_scan_xy_start.setObjectName("action_scan_xy_start")
        self.action_scan_xy_resume = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/22x22/scan-xy-resume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_scan_xy_resume.setIcon(icon5)
        self.action_scan_xy_resume.setObjectName("action_scan_xy_resume")
        self.action_scan_depth_start = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/22x22/scan-depth-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_scan_depth_start.setIcon(icon6)
        self.action_scan_depth_start.setObjectName("action_scan_depth_start")
        self.action_scan_depth_resume = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/22x22/scan-depth-resume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_scan_depth_resume.setIcon(icon7)
        self.action_scan_depth_resume.setObjectName("action_scan_depth_resume")
        self.action_optimize_position = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/22x22/optimize-position.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_optimize_position.setIcon(icon8)
        self.action_optimize_position.setStatusTip("")
        self.action_optimize_position.setObjectName("action_optimize_position")
        self.action_stop_scanning = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/22x22/stop-scan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_stop_scanning.setIcon(icon9)
        self.action_stop_scanning.setObjectName("action_stop_scanning")
        self.restore_default_view_Action = QtWidgets.QAction(MainWindow)
        self.restore_default_view_Action.setObjectName("restore_default_view_Action")
        self.optimizer_only_view_Action = QtWidgets.QAction(MainWindow)
        self.optimizer_only_view_Action.setIcon(icon8)
        self.optimizer_only_view_Action.setObjectName("optimizer_only_view_Action")
        self.actionScan_Toolbar = QtWidgets.QAction(MainWindow)
        self.actionScan_Toolbar.setCheckable(True)
        self.actionScan_Toolbar.setChecked(True)
        self.actionScan_Toolbar.setObjectName("actionScan_Toolbar")
        self.actionUtil_Toolbar = QtWidgets.QAction(MainWindow)
        self.actionUtil_Toolbar.setCheckable(True)
        self.actionUtil_Toolbar.setChecked(True)
        self.actionUtil_Toolbar.setObjectName("actionUtil_Toolbar")
        self.action_TiltCorrection = QtWidgets.QAction(MainWindow)
        self.action_TiltCorrection.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../artwork/icons/qudiTheme/22x22/correct-tilt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_TiltCorrection.setIcon(icon10)
        self.action_TiltCorrection.setObjectName("action_TiltCorrection")
        self.actionTilt_correction_view = QtWidgets.QAction(MainWindow)
        self.actionTilt_correction_view.setCheckable(True)
        self.actionTilt_correction_view.setObjectName("actionTilt_correction_view")
        self.actionForward = QtWidgets.QAction(MainWindow)
        self.actionForward.setEnabled(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon11)
        self.actionForward.setObjectName("actionForward")
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setEnabled(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon12)
        self.actionBack.setObjectName("actionBack")
        self.actionScan_line_view = QtWidgets.QAction(MainWindow)
        self.actionScan_line_view.setCheckable(True)
        self.actionScan_line_view.setObjectName("actionScan_line_view")
        self.action_full_range_xy = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/zoom-fit-best.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_full_range_xy.setIcon(icon13)
        self.action_full_range_xy.setObjectName("action_full_range_xy")
        self.action_full_range_z = QtWidgets.QAction(MainWindow)
        self.action_full_range_z.setIcon(icon13)
        self.action_full_range_z.setObjectName("action_full_range_z")
        self.actionAutoRange_xy = QtWidgets.QAction(MainWindow)
        self.actionAutoRange_xy.setCheckable(False)
        self.actionAutoRange_xy.setObjectName("actionAutoRange_xy")
        self.actionAutoRange_z = QtWidgets.QAction(MainWindow)
        self.actionAutoRange_z.setObjectName("actionAutoRange_z")
        self.actionBlink_correction_view = QtWidgets.QAction(MainWindow)
        self.actionBlink_correction_view.setCheckable(True)
        self.actionBlink_correction_view.setObjectName("actionBlink_correction_view")
        self.actionUse_LT_limits = QtWidgets.QAction(MainWindow)
        self.actionUse_LT_limits.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../artwork/icons/oxygen/22x22/LT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUse_LT_limits.setIcon(icon14)
        self.actionUse_LT_limits.setObjectName("actionUse_LT_limits")
        self.actionSave_config = QtWidgets.QAction(MainWindow)
        self.actionSave_config.setIcon(icon)
        self.actionSave_config.setObjectName("actionSave_config")
        self.actionSetPOIs = QtWidgets.QAction(MainWindow)
        self.actionSetPOIs.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("C:/Users/YY3/Downloads/cross_hair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetPOIs.setIcon(icon15)
        self.actionSetPOIs.setObjectName("actionSetPOIs")
        self.menuFile.addAction(self.actionSave_XY_Scan)
        self.menuFile.addAction(self.actionSave_Depth_Scan)
        self.menuFile.addAction(self.actionSave_configuration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menu_Options.addAction(self.action_Settings)
        self.menu_Options.addAction(self.action_optimizer_settings)
        self.menuToolbars.addAction(self.actionScan_Toolbar)
        self.menuToolbars.addAction(self.actionUtil_Toolbar)
        self.menuView.addAction(self.actionXY_scan_view)
        self.menuView.addAction(self.actionDepth_scan_view)
        self.menuView.addAction(self.actionScan_control_view)
        self.menuView.addAction(self.actionOptimizer_view)
        self.menuView.addAction(self.actionScan_line_view)
        self.menuView.addAction(self.actionTilt_correction_view)
        self.menuView.addAction(self.actionBlink_correction_view)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.restore_default_view_Action)
        self.menuView.addSeparator()
        self.menuView.addAction(self.optimizer_only_view_Action)
        self.menuView.addAction(self.actionAutoRange_xy)
        self.menuView.addAction(self.actionAutoRange_z)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.scan_ToolBar.addAction(self.action_scan_xy_start)
        self.scan_ToolBar.addAction(self.action_scan_xy_resume)
        self.scan_ToolBar.addAction(self.action_stop_scanning)
        self.scan_ToolBar.addAction(self.action_scan_depth_start)
        self.scan_ToolBar.addAction(self.action_scan_depth_resume)
        self.scan_ToolBar.addAction(self.action_optimize_position)
        self.util_ToolBar.addAction(self.action_zoom)
        self.util_ToolBar.addAction(self.action_full_range_xy)
        self.util_ToolBar.addAction(self.action_full_range_z)
        self.util_ToolBar.addAction(self.actionSetPOIs)
        self.util_ToolBar.addAction(self.action_TiltCorrection)
        self.historyToolBar.addAction(self.actionBack)
        self.historyToolBar.addAction(self.actionForward)
        self.limitsToolBar.addAction(self.actionUse_LT_limits)
        self.limitsToolBar.addAction(self.actionSave_config)

        self.retranslateUi(MainWindow)
        self.actionClose.triggered.connect(MainWindow.close)
        self.actionXY_scan_view.triggered['bool'].connect(self.xy_scan_dockWidget.setVisible)
        self.xy_scan_dockWidget.visibilityChanged['bool'].connect(self.actionXY_scan_view.setChecked)
        self.actionDepth_scan_view.triggered['bool'].connect(self.depth_scan_dockWidget.setVisible)
        self.depth_scan_dockWidget.visibilityChanged['bool'].connect(self.actionDepth_scan_view.setChecked)
        self.actionScan_control_view.triggered['bool'].connect(self.scan_control_dockWidget.setVisible)
        self.scan_control_dockWidget.visibilityChanged['bool'].connect(self.actionScan_control_view.setChecked)
        self.actionOptimizer_view.triggered['bool'].connect(self.optimizer_dockWidget.setVisible)
        self.optimizer_dockWidget.visibilityChanged['bool'].connect(self.actionOptimizer_view.setChecked)
        self.actionScan_Toolbar.triggered['bool'].connect(self.scan_ToolBar.setVisible)
        self.actionUtil_Toolbar.triggered['bool'].connect(self.util_ToolBar.setVisible)
        self.actionTilt_correction_view.triggered['bool'].connect(self.tilt_correction_dockWidget.setVisible)
        self.scan_ToolBar.visibilityChanged['bool'].connect(self.actionScan_Toolbar.setChecked)
        self.util_ToolBar.visibilityChanged['bool'].connect(self.actionUtil_Toolbar.setChecked)
        self.tilt_correction_dockWidget.visibilityChanged['bool'].connect(self.actionTilt_correction_view.setChecked)
        self.actionScan_line_view.triggered['bool'].connect(self.scanLineDockWidget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.xy_res_InputWidget, self.z_res_InputWidget)
        MainWindow.setTabOrder(self.z_res_InputWidget, self.x_min_InputWidget)
        MainWindow.setTabOrder(self.x_min_InputWidget, self.x_max_InputWidget)
        MainWindow.setTabOrder(self.x_max_InputWidget, self.y_min_InputWidget)
        MainWindow.setTabOrder(self.y_min_InputWidget, self.y_max_InputWidget)
        MainWindow.setTabOrder(self.y_max_InputWidget, self.z_min_InputWidget)
        MainWindow.setTabOrder(self.z_min_InputWidget, self.z_max_InputWidget)
        MainWindow.setTabOrder(self.z_max_InputWidget, self.x_current_InputWidget)
        MainWindow.setTabOrder(self.x_current_InputWidget, self.y_current_InputWidget)
        MainWindow.setTabOrder(self.y_current_InputWidget, self.z_current_InputWidget)
        MainWindow.setTabOrder(self.z_current_InputWidget, self.xy_cb_max_DoubleSpinBox)
        MainWindow.setTabOrder(self.xy_cb_max_DoubleSpinBox, self.xy_cb_high_percentile_DoubleSpinBox)
        MainWindow.setTabOrder(self.xy_cb_high_percentile_DoubleSpinBox, self.xy_cb_ViewWidget)
        MainWindow.setTabOrder(self.xy_cb_ViewWidget, self.xy_cb_low_percentile_DoubleSpinBox)
        MainWindow.setTabOrder(self.xy_cb_low_percentile_DoubleSpinBox, self.xy_cb_min_DoubleSpinBox)
        MainWindow.setTabOrder(self.xy_cb_min_DoubleSpinBox, self.xy_cb_centiles_RadioButton)
        MainWindow.setTabOrder(self.xy_cb_centiles_RadioButton, self.xy_cb_manual_RadioButton)
        MainWindow.setTabOrder(self.xy_cb_manual_RadioButton, self.depth_cb_max_DoubleSpinBox)
        MainWindow.setTabOrder(self.depth_cb_max_DoubleSpinBox, self.depth_cb_high_percentile_DoubleSpinBox)
        MainWindow.setTabOrder(self.depth_cb_high_percentile_DoubleSpinBox, self.depth_cb_ViewWidget)
        MainWindow.setTabOrder(self.depth_cb_ViewWidget, self.depth_cb_low_percentile_DoubleSpinBox)
        MainWindow.setTabOrder(self.depth_cb_low_percentile_DoubleSpinBox, self.depth_cb_min_DoubleSpinBox)
        MainWindow.setTabOrder(self.depth_cb_min_DoubleSpinBox, self.depth_cb_centiles_RadioButton)
        MainWindow.setTabOrder(self.depth_cb_centiles_RadioButton, self.depth_cb_manual_RadioButton)
        MainWindow.setTabOrder(self.depth_cb_manual_RadioButton, self.tilt_set_01_pushButton)
        MainWindow.setTabOrder(self.tilt_set_01_pushButton, self.tilt_set_02_pushButton)
        MainWindow.setTabOrder(self.tilt_set_02_pushButton, self.tilt_set_03_pushButton)
        MainWindow.setTabOrder(self.tilt_set_03_pushButton, self.calc_tilt_pushButton)
        MainWindow.setTabOrder(self.calc_tilt_pushButton, self.tilt_01_x_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_01_x_pos_doubleSpinBox, self.tilt_01_y_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_01_y_pos_doubleSpinBox, self.tilt_01_z_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_01_z_pos_doubleSpinBox, self.tilt_02_x_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_02_x_pos_doubleSpinBox, self.tilt_02_y_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_02_y_pos_doubleSpinBox, self.tilt_02_z_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_02_z_pos_doubleSpinBox, self.tilt_03_x_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_03_x_pos_doubleSpinBox, self.tilt_03_y_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_03_y_pos_doubleSpinBox, self.tilt_03_z_pos_doubleSpinBox)
        MainWindow.setTabOrder(self.tilt_03_z_pos_doubleSpinBox, self.x_SliderWidget)
        MainWindow.setTabOrder(self.x_SliderWidget, self.depth_refocus_ViewWidget_2)
        MainWindow.setTabOrder(self.depth_refocus_ViewWidget_2, self.z_SliderWidget)
        MainWindow.setTabOrder(self.z_SliderWidget, self.xy_refocus_ViewWidget_2)
        MainWindow.setTabOrder(self.xy_refocus_ViewWidget_2, self.depth_ViewWidget)
        MainWindow.setTabOrder(self.depth_ViewWidget, self.y_SliderWidget)
        MainWindow.setTabOrder(self.y_SliderWidget, self.xy_ViewWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qudi: Confocal"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menu_Options.setTitle(_translate("MainWindow", "Option&s"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuToolbars.setTitle(_translate("MainWindow", "Too&lbars"))
        self.depth_scan_dockWidget.setWindowTitle(_translate("MainWindow", "Depth scan"))
        self.depth_cb_max_DoubleSpinBox.setSuffix(_translate("MainWindow", "c/s"))
        self.depth_cb_high_percentile_DoubleSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.depth_cb_low_percentile_DoubleSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.depth_cb_min_DoubleSpinBox.setSuffix(_translate("MainWindow", "c/s"))
        self.depth_cb_centiles_RadioButton.setText(_translate("MainWindow", "Percenti&les"))
        self.depth_cb_manual_RadioButton.setText(_translate("MainWindow", "Man&ual"))
        self.optimizer_dockWidget.setWindowTitle(_translate("MainWindow", "Optimizer"))
        self.label_9.setText(_translate("MainWindow", "(x,y,z): "))
        self.refocus_position_label.setToolTip(_translate("MainWindow", "This text is selectable.  Copy and paste into labnotes."))
        self.refocus_position_label.setText(_translate("MainWindow", "(?, ?, ?)"))
        self.scan_control_dockWidget.setWindowTitle(_translate("MainWindow", "Scan parameters"))
        self.resolutionLabel.setText(_translate("MainWindow", "Resolution"))
        self.scanrangeLabel.setText(_translate("MainWindow", "Scan Range"))
        self.xAxisLabel.setText(_translate("MainWindow", "X-Axis :"))
        self.xy_res_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">XY-Resolution</span></p></body></html>"))
        self.x_max_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X_Max</span></p></body></html>"))
        self.x_current_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X-position</span></p></body></html>"))
        self.yAxisLabel.setText(_translate("MainWindow", "Y-Axis :"))
        self.y_min_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y_Min</span></p></body></html>"))
        self.y_max_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y_Max</span></p></body></html>"))
        self.y_current_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y-position</span></p></body></html>"))
        self.zAxisLabel.setText(_translate("MainWindow", "Z-Axis :"))
        self.z_res_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z-Resolution</span></p></body></html>"))
        self.z_min_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z_Min</span></p></body></html>"))
        self.z_max_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z_Max</span></p></body></html>"))
        self.z_current_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Z-position</span></p></body></html>"))
        self.x_min_InputWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X_Min</span></p></body></html>"))
        self.xy_scan_dockWidget.setWindowTitle(_translate("MainWindow", "XY scan"))
        self.xy_cb_max_DoubleSpinBox.setSuffix(_translate("MainWindow", "c/s"))
        self.xy_cb_high_percentile_DoubleSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.xy_cb_low_percentile_DoubleSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.xy_cb_min_DoubleSpinBox.setSuffix(_translate("MainWindow", "c/s"))
        self.xy_cb_centiles_RadioButton.setText(_translate("MainWindow", "Percentiles"))
        self.xy_cb_manual_RadioButton.setText(_translate("MainWindow", "Manual"))
        self.scan_ToolBar.setWindowTitle(_translate("MainWindow", "Scan toolbar"))
        self.util_ToolBar.setWindowTitle(_translate("MainWindow", "Utilities Toolbar"))
        self.tilt_correction_dockWidget.setWindowTitle(_translate("MainWindow", "Tilt correction"))
        self.calc_tilt_pushButton.setText(_translate("MainWindow", "Calc. Tilit"))
        self.tilt_set_02_pushButton.setText(_translate("MainWindow", "02"))
        self.tilt_set_03_pushButton.setText(_translate("MainWindow", "03"))
        self.tilt_set_01_pushButton.setText(_translate("MainWindow", "01"))
        self.tiltpoint_label.setText(_translate("MainWindow", "Set Tiltpoint :"))
        self.tilt_x_label.setText(_translate("MainWindow", "X"))
        self.tilt_y_label.setText(_translate("MainWindow", "Y"))
        self.tilt_z_label.setText(_translate("MainWindow", "Z"))
        self.historyToolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.scanLineDockWidget.setWindowTitle(_translate("MainWindow", "Scan line"))
        self.limitsToolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave_XY_Scan.setText(_translate("MainWindow", "&Save XY scan"))
        self.actionSave_configuration.setText(_translate("MainWindow", "Save co&nfiguration"))
        self.action_Settings.setText(_translate("MainWindow", "Se&ttings"))
        self.actionClose.setText(_translate("MainWindow", "C&lose"))
        self.actionClose.setToolTip(_translate("MainWindow", "Close confocal. Shortcut:Ctrl+W"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSave_Depth_Scan.setText(_translate("MainWindow", "Save &Depth scan"))
        self.actionSave_Depth_Scan.setToolTip(_translate("MainWindow", "Save Depth Data"))
        self.action_optimizer_settings.setText(_translate("MainWindow", "O&ptimizer Settings"))
        self.action_zoom.setText(_translate("MainWindow", "Zoom"))
        self.action_zoom.setToolTip(_translate("MainWindow", "Shortcut:Z"))
        self.action_zoom.setShortcut(_translate("MainWindow", "Z"))
        self.actionXY_scan_view.setText(_translate("MainWindow", "&XY scan"))
        self.actionXY_scan_view.setToolTip(_translate("MainWindow", "Shortcut:Alt+X"))
        self.actionXY_scan_view.setShortcut(_translate("MainWindow", "Alt+X"))
        self.actionDepth_scan_view.setText(_translate("MainWindow", "&Depth scan"))
        self.actionDepth_scan_view.setToolTip(_translate("MainWindow", "Shortcut:Alt+D"))
        self.actionDepth_scan_view.setShortcut(_translate("MainWindow", "Alt+D"))
        self.actionScan_control_view.setText(_translate("MainWindow", "&Scan parameters"))
        self.actionOptimizer_view.setText(_translate("MainWindow", "&Optimizer"))
        self.actionOptimizer_view.setToolTip(_translate("MainWindow", "Shortcut:Alt+O"))
        self.actionOptimizer_view.setShortcut(_translate("MainWindow", "Alt+O"))
        self.action_scan_xy_start.setText(_translate("MainWindow", "Scan XY"))
        self.action_scan_xy_start.setToolTip(_translate("MainWindow", "Start a fresh XY scan. Shortcut:Shift+S"))
        self.action_scan_xy_start.setShortcut(_translate("MainWindow", "Shift+S"))
        self.action_scan_xy_resume.setText(_translate("MainWindow", "Resume XY scan"))
        self.action_scan_xy_resume.setToolTip(_translate("MainWindow", "Resume an interrupted XY scan. Shortcut:Shift+R"))
        self.action_scan_xy_resume.setShortcut(_translate("MainWindow", "Shift+R"))
        self.action_scan_depth_start.setText(_translate("MainWindow", "Scan depth"))
        self.action_scan_depth_start.setToolTip(_translate("MainWindow", "Start a fresh depth scan. Shortcut:Shift+D"))
        self.action_scan_depth_start.setShortcut(_translate("MainWindow", "Shift+D"))
        self.action_scan_depth_resume.setText(_translate("MainWindow", "Resume depth scan"))
        self.action_scan_depth_resume.setToolTip(_translate("MainWindow", "Resume an interrupted depth scan"))
        self.action_optimize_position.setText(_translate("MainWindow", "&Optimize position"))
        self.action_optimize_position.setToolTip(_translate("MainWindow", "Optimize position of crosshair. Shortcut:Ctrl+Alt+X"))
        self.action_optimize_position.setShortcut(_translate("MainWindow", "Ctrl+Alt+X"))
        self.action_stop_scanning.setText(_translate("MainWindow", "Stop scan"))
        self.action_stop_scanning.setToolTip(_translate("MainWindow", "Stop scanning XY or depth and return to \"ready\" state. Shortcut:Shift+E"))
        self.action_stop_scanning.setShortcut(_translate("MainWindow", "Shift+E"))
        self.restore_default_view_Action.setText(_translate("MainWindow", "&Restore default"))
        self.restore_default_view_Action.setToolTip(_translate("MainWindow", "Restore default arrangement of dock widgets "))
        self.optimizer_only_view_Action.setText(_translate("MainWindow", "O&ptimizer-only"))
        self.optimizer_only_view_Action.setToolTip(_translate("MainWindow", "Rearrange window as a small optimizer interface."))
        self.actionScan_Toolbar.setText(_translate("MainWindow", "&Scan Toolbar"))
        self.actionScan_Toolbar.setToolTip(_translate("MainWindow", "This toolbar contains all the scan actions that let you record images in the confocal microscope"))
        self.actionUtil_Toolbar.setText(_translate("MainWindow", "&Util Toolbar"))
        self.action_TiltCorrection.setText(_translate("MainWindow", "&Use Tilt Correction"))
        self.actionTilt_correction_view.setText(_translate("MainWindow", "&Tilt correction"))
        self.actionForward.setText(_translate("MainWindow", "&Forward"))
        self.actionForward.setToolTip(_translate("MainWindow", "Go forward in scan history. Shortcut:Ctrl+R"))
        self.actionForward.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionBack.setText(_translate("MainWindow", "&Back"))
        self.actionBack.setToolTip(_translate("MainWindow", "Go back in scan history. Shortcut:Ctrl+Z"))
        self.actionBack.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionScan_line_view.setText(_translate("MainWindow", "Scan line"))
        self.actionScan_line_view.setToolTip(_translate("MainWindow", "Show or hide scan line display"))
        self.action_full_range_xy.setText(_translate("MainWindow", "Full range XY"))
        self.action_full_range_xy.setToolTip(_translate("MainWindow", "Set X and Y directions to full scan range. Shortcut:Ctrl+Alt+<"))
        self.action_full_range_xy.setShortcut(_translate("MainWindow", "Ctrl+Alt+<"))
        self.action_full_range_z.setText(_translate("MainWindow", "Full range Z"))
        self.action_full_range_z.setToolTip(_translate("MainWindow", "Set Z direction to full scan range. Shortcut:Ctrl+Alt+Y"))
        self.action_full_range_z.setShortcut(_translate("MainWindow", "Ctrl+Alt+Y"))
        self.actionAutoRange_xy.setText(_translate("MainWindow", "autoRange_xy"))
        self.actionAutoRange_xy.setToolTip(_translate("MainWindow", "Shortcut:Shift+X"))
        self.actionAutoRange_xy.setShortcut(_translate("MainWindow", "Shift+X"))
        self.actionAutoRange_z.setText(_translate("MainWindow", "autoRange_z"))
        self.actionAutoRange_z.setToolTip(_translate("MainWindow", "Shortcut:Shift+C"))
        self.actionAutoRange_z.setShortcut(_translate("MainWindow", "Shift+C"))
        self.actionBlink_correction_view.setText(_translate("MainWindow", "&Blink correction"))
        self.actionBlink_correction_view.setToolTip(_translate("MainWindow", "Blink correction"))
        self.actionUse_LT_limits.setText(_translate("MainWindow", "Use LT limits"))
        self.actionUse_LT_limits.setToolTip(_translate("MainWindow", "DANGER! Only press this if you are at LT! This increases the voltage limit on the piezos."))
        self.actionSave_config.setText(_translate("MainWindow", "Save config"))
        self.actionSetPOIs.setText(_translate("MainWindow", "Set POIs"))
        self.actionSetPOIs.setShortcut(_translate("MainWindow", "Ctrl+P"))

from pyqtgraph import PlotWidget
from qtwidgets.scan_plotwidget import ScanPlotWidget
from qtwidgets.scientific_spinbox import ScienDSpinBox
