# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/vladislavbushmakin/Desktop/qudi/gui/confocal/ui_optim_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(468, 388)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.settings_tabWidget.setObjectName("settings_tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout.setObjectName("gridLayout")
        self.return_slow_label = QtWidgets.QLabel(self.tab_1)
        self.return_slow_label.setObjectName("return_slow_label")
        self.gridLayout.addWidget(self.return_slow_label, 4, 0, 1, 2)
        self.count_freq_label = QtWidgets.QLabel(self.tab_1)
        self.count_freq_label.setObjectName("count_freq_label")
        self.gridLayout.addWidget(self.count_freq_label, 3, 0, 1, 1)
        self.xy_optimizer_range_DoubleSpinBox = ScienDSpinBox(self.tab_1)
        self.xy_optimizer_range_DoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.xy_optimizer_range_DoubleSpinBox.setSpecialValueText("")
        self.xy_optimizer_range_DoubleSpinBox.setDecimals(3)
        self.xy_optimizer_range_DoubleSpinBox.setMaximum(1.0)
        self.xy_optimizer_range_DoubleSpinBox.setSingleStep(1e-06)
        self.xy_optimizer_range_DoubleSpinBox.setProperty("value", 1.0)
        self.xy_optimizer_range_DoubleSpinBox.setObjectName("xy_optimizer_range_DoubleSpinBox")
        self.gridLayout.addWidget(self.xy_optimizer_range_DoubleSpinBox, 0, 1, 1, 1)
        self.xy_res_label = QtWidgets.QLabel(self.tab_1)
        self.xy_res_label.setObjectName("xy_res_label")
        self.gridLayout.addWidget(self.xy_res_label, 0, 2, 1, 1)
        self.xy_range_label = QtWidgets.QLabel(self.tab_1)
        self.xy_range_label.setObjectName("xy_range_label")
        self.gridLayout.addWidget(self.xy_range_label, 0, 0, 1, 1)
        self.opt_sequence_label = QtWidgets.QLabel(self.tab_1)
        self.opt_sequence_label.setObjectName("opt_sequence_label")
        self.gridLayout.addWidget(self.opt_sequence_label, 6, 0, 1, 1)
        self.z_res_label = QtWidgets.QLabel(self.tab_1)
        self.z_res_label.setObjectName("z_res_label")
        self.gridLayout.addWidget(self.z_res_label, 1, 2, 1, 1)
        self.count_freq_SpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.count_freq_SpinBox.setMaximum(10000)
        self.count_freq_SpinBox.setProperty("value", 50)
        self.count_freq_SpinBox.setObjectName("count_freq_SpinBox")
        self.gridLayout.addWidget(self.count_freq_SpinBox, 3, 2, 1, 1)
        self.z_optimizer_range_DoubleSpinBox = ScienDSpinBox(self.tab_1)
        self.z_optimizer_range_DoubleSpinBox.setDecimals(3)
        self.z_optimizer_range_DoubleSpinBox.setMaximum(5.0)
        self.z_optimizer_range_DoubleSpinBox.setSingleStep(0.01)
        self.z_optimizer_range_DoubleSpinBox.setProperty("value", 2.0)
        self.z_optimizer_range_DoubleSpinBox.setObjectName("z_optimizer_range_DoubleSpinBox")
        self.gridLayout.addWidget(self.z_optimizer_range_DoubleSpinBox, 1, 1, 1, 1)
        self.do_surface_subtraction_CheckBox = QtWidgets.QCheckBox(self.tab_1)
        self.do_surface_subtraction_CheckBox.setObjectName("do_surface_subtraction_CheckBox")
        self.gridLayout.addWidget(self.do_surface_subtraction_CheckBox, 7, 0, 1, 2)
        self.optimization_sequence_lineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.optimization_sequence_lineEdit.setObjectName("optimization_sequence_lineEdit")
        self.gridLayout.addWidget(self.optimization_sequence_lineEdit, 6, 2, 1, 2)
        self.z_optimizer_resolution_SpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.z_optimizer_resolution_SpinBox.setMinimum(1)
        self.z_optimizer_resolution_SpinBox.setProperty("value", 30)
        self.z_optimizer_resolution_SpinBox.setObjectName("z_optimizer_resolution_SpinBox")
        self.gridLayout.addWidget(self.z_optimizer_resolution_SpinBox, 1, 3, 1, 1)
        self.hw_settle_label = QtWidgets.QLabel(self.tab_1)
        self.hw_settle_label.setObjectName("hw_settle_label")
        self.gridLayout.addWidget(self.hw_settle_label, 5, 0, 1, 1)
        self.hw_settle_time_SpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.hw_settle_time_SpinBox.setMaximum(1000)
        self.hw_settle_time_SpinBox.setProperty("value", 100)
        self.hw_settle_time_SpinBox.setObjectName("hw_settle_time_SpinBox")
        self.gridLayout.addWidget(self.hw_settle_time_SpinBox, 5, 2, 1, 1)
        self.return_slow_SpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.return_slow_SpinBox.setMaximum(1000)
        self.return_slow_SpinBox.setProperty("value", 20)
        self.return_slow_SpinBox.setObjectName("return_slow_SpinBox")
        self.gridLayout.addWidget(self.return_slow_SpinBox, 4, 2, 1, 1)
        self.z_range_label = QtWidgets.QLabel(self.tab_1)
        self.z_range_label.setObjectName("z_range_label")
        self.gridLayout.addWidget(self.z_range_label, 1, 0, 1, 1)
        self.xy_optimizer_resolution_SpinBox = QtWidgets.QSpinBox(self.tab_1)
        self.xy_optimizer_resolution_SpinBox.setMinimum(1)
        self.xy_optimizer_resolution_SpinBox.setProperty("value", 10)
        self.xy_optimizer_resolution_SpinBox.setObjectName("xy_optimizer_resolution_SpinBox")
        self.gridLayout.addWidget(self.xy_optimizer_resolution_SpinBox, 0, 3, 1, 1)
        self.opt_channel_label = QtWidgets.QLabel(self.tab_1)
        self.opt_channel_label.setObjectName("opt_channel_label")
        self.gridLayout.addWidget(self.opt_channel_label, 2, 0, 1, 1)
        self.opt_channel_ComboBox = QtWidgets.QComboBox(self.tab_1)
        self.opt_channel_ComboBox.setObjectName("opt_channel_ComboBox")
        self.gridLayout.addWidget(self.opt_channel_ComboBox, 2, 2, 1, 1)
        self.settings_tabWidget.addTab(self.tab_1, "")
        self.verticalLayout.addWidget(self.settings_tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.settings_tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "qudi: Optimizer - Settings"))
        self.return_slow_label.setToolTip(_translate("SettingsDialog", "Resolution (number of steps) in the return scan that occurs between each line of the XY scan."))
        self.return_slow_label.setText(_translate("SettingsDialog", "return slowdown (points):"))
        self.count_freq_label.setToolTip(_translate("SettingsDialog", "Frequency at which the scan pixels are acquired."))
        self.count_freq_label.setText(_translate("SettingsDialog", "Count frequency (Hz):"))
        self.xy_optimizer_range_DoubleSpinBox.setToolTip(_translate("SettingsDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Scan range of the optimizer in the xy area.</span></p></body></html>"))
        self.xy_optimizer_range_DoubleSpinBox.setSuffix(_translate("SettingsDialog", "m"))
        self.xy_res_label.setText(_translate("SettingsDialog", "XY Resolution:"))
        self.xy_range_label.setToolTip(_translate("SettingsDialog", "<html><head/><body><p><br/></p></body></html>"))
        self.xy_range_label.setText(_translate("SettingsDialog", "XY Range:"))
        self.opt_sequence_label.setText(_translate("SettingsDialog", "Optimization sequence: "))
        self.z_res_label.setText(_translate("SettingsDialog", "Z Resolution:"))
        self.count_freq_SpinBox.setToolTip(_translate("SettingsDialog", "Frequency at which the scan pixels are acquired."))
        self.z_optimizer_range_DoubleSpinBox.setToolTip(_translate("SettingsDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Scan range of the optimizer in the z direction.</span></p></body></html>"))
        self.z_optimizer_range_DoubleSpinBox.setSuffix(_translate("SettingsDialog", "m"))
        self.do_surface_subtraction_CheckBox.setToolTip(_translate("SettingsDialog", "Perform a second depth scan displaced sideways (in X), and subtract to remove surface brightness from the optimizer depth scan."))
        self.do_surface_subtraction_CheckBox.setText(_translate("SettingsDialog", "Do surface subtraction in depth-scan"))
        self.optimization_sequence_lineEdit.setText(_translate("SettingsDialog", "XY, Z"))
        self.z_optimizer_resolution_SpinBox.setToolTip(_translate("SettingsDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Specify the distance between two subsequent scanned points for optimizer z scan.</span></p></body></html>"))
        self.hw_settle_label.setToolTip(_translate("SettingsDialog", "Settle time to let the scanning HW reach the start-point of the optimization scans."))
        self.hw_settle_label.setText(_translate("SettingsDialog", "HW settle time (ms)"))
        self.hw_settle_time_SpinBox.setToolTip(_translate("SettingsDialog", "Settle time to let the scanning HW reach the start-point of the optimization scans."))
        self.return_slow_SpinBox.setToolTip(_translate("SettingsDialog", "Resolution (number of steps) in the return scan that occurs between each line of the XY scan."))
        self.z_range_label.setText(_translate("SettingsDialog", "Z Range:"))
        self.xy_optimizer_resolution_SpinBox.setToolTip(_translate("SettingsDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Specify the distance between two subsequent scanned points for optimizer in xy scan.</span></p></body></html>"))
        self.opt_channel_label.setText(_translate("SettingsDialog", "Channel to optimize"))
        self.settings_tabWidget.setTabText(self.settings_tabWidget.indexOf(self.tab_1), _translate("SettingsDialog", "General"))

from qtwidgets.scientific_spinbox import ScienDSpinBox
