from PyQt5 import QtCore
class current_measurement_default_gui():
        def initialize_connections_and_defaultvalues(self):
                #set the default values to the text line
                self._mw.scan_stop_V_doubleSpinBox.valueChanged.connect(self._current_measurement.scan_stop_V_doubleSpinBox_Edited,type=QtCore.Qt.QueuedConnection)
                self._mw.offset_doubleSpinBox.valueChanged.connect(self._current_measurement.offset_doubleSpinBox_Edited,type=QtCore.Qt.QueuedConnection)
                self._mw.stabilization_wait_time_doubleSpinBox.valueChanged.connect(self._current_measurement.stabilization_wait_time_doubleSpinBox_Edited,type=QtCore.Qt.QueuedConnection)
                self._mw.scan_start_V_doubleSpinBox.valueChanged.connect(self._current_measurement.scan_start_V_doubleSpinBox_Edited,type=QtCore.Qt.QueuedConnection)
                self._mw.save_after_scan_checkBox.stateChanged.connect(self._current_measurement.save_after_scan_checkBox_StateChanged,type=QtCore.Qt.QueuedConnection)
                self._mw.Data_Points_LineEdit.textEdited.connect(self._current_measurement.Data_Points_LineEdit_textEdited,type=QtCore.Qt.QueuedConnection)
                self._mw.SaveTrace_PushButton.clicked.connect(self._current_measurement.SaveTrace_PushButton_Clicked,type=QtCore.Qt.QueuedConnection)
                self._mw.applied_voltage_doubleSpinBox.valueChanged.connect(self._current_measurement.applied_voltage_doubleSpinBox_Edited,type=QtCore.Qt.QueuedConnection)
                self._mw.Multiplier_doubleSpinBox.valueChanged.connect(self._current_measurement.Multiplier_doubleSpinBox_Edited,type=QtCore.Qt.QueuedConnection)
                self._mw.step_doubleSpinBox.valueChanged.connect(self._current_measurement.step_doubleSpinBox_Edited,type=QtCore.Qt.QueuedConnection)
                self._mw.name_lineEdit.textEdited.connect(self._current_measurement.name_lineEdit_textEdited,type=QtCore.Qt.QueuedConnection)
                self._mw.start_scan_pushButton.clicked.connect(self._current_measurement.start_scan_pushButton_Clicked,type=QtCore.Qt.QueuedConnection)
                self._mw.safe_limits_checkBox.stateChanged.connect(self._current_measurement.safe_limits_checkBox_StateChanged,type=QtCore.Qt.QueuedConnection)

                self._mw.scan_stop_V_doubleSpinBox.setValue(self._current_measurement.scan_stop_V)
                self._mw.offset_doubleSpinBox.setValue(float(self._current_measurement.offset))
                self._mw.stabilization_wait_time_doubleSpinBox.setValue(self._current_measurement.stabilization_wait_time)
                self._mw.scan_start_V_doubleSpinBox.setValue(self._current_measurement.scan_start_V)
                self._mw.save_after_scan_checkBox.setChecked(self._current_measurement.save_after_scan)
                self._mw.Data_Points_LineEdit.setText(str(self._current_measurement.Data_Points))
                self._mw.applied_voltage_doubleSpinBox.setValue(self._current_measurement.applied_voltage)
                self._mw.Multiplier_doubleSpinBox.setValue(float(self._current_measurement.Multiplier))
                self._mw.step_doubleSpinBox.setValue(self._current_measurement.step)
                self._mw.name_lineEdit.setText(str(self._current_measurement.name))
                self._mw.safe_limits_checkBox.setChecked(self._current_measurement.safe_limits)

        def disconnect_all(self):
                self._mw.scan_stop_V_doubleSpinBox.valueChanged.disconnect()
                self._mw.offset_doubleSpinBox.valueChanged.disconnect()
                self._mw.stabilization_wait_time_doubleSpinBox.valueChanged.disconnect()
                self._mw.scan_start_V_doubleSpinBox.valueChanged.disconnect()
                self._mw.save_after_scan_checkBox.stateChanged.disconnect()
                self._mw.Data_Points_LineEdit.textEdited.disconnect()
                self._mw.SaveTrace_PushButton.clicked.disconnect()
                self._mw.applied_voltage_doubleSpinBox.valueChanged.disconnect()
                self._mw.Multiplier_doubleSpinBox.valueChanged.disconnect()
                self._mw.step_doubleSpinBox.valueChanged.disconnect()
                self._mw.name_lineEdit.textEdited.disconnect()
                self._mw.start_scan_pushButton.clicked.disconnect()
                self._mw.safe_limits_checkBox.stateChanged.disconnect()