# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\pi3diamond\qtgui\pi3d_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(666, 330)
        window.setWindowOpacity(1.0)
        window.setAutoFillBackground(False)
        self.widget = QtWidgets.QWidget(window)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_script_folder_text_field = QtWidgets.QTextBrowser(self.widget)
        self.user_script_folder_text_field.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_script_folder_text_field.sizePolicy().hasHeightForWidth())
        self.user_script_folder_text_field.setSizePolicy(sizePolicy)
        self.user_script_folder_text_field.setMinimumSize(QtCore.QSize(300, 0))
        self.user_script_folder_text_field.setMaximumSize(QtCore.QSize(16777215, 24))
        self.user_script_folder_text_field.setReadOnly(False)
        self.user_script_folder_text_field.setObjectName("user_script_folder_text_field")
        self.horizontalLayout_2.addWidget(self.user_script_folder_text_field)
        self.user_script_folder_pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_script_folder_pushButton.sizePolicy().hasHeightForWidth())
        self.user_script_folder_pushButton.setSizePolicy(sizePolicy)
        self.user_script_folder_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("folder_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.user_script_folder_pushButton.setIcon(icon)
        self.user_script_folder_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.user_script_folder_pushButton.setObjectName("user_script_folder_pushButton")
        self.horizontalLayout_2.addWidget(self.user_script_folder_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.selected_user_script_combo_box = QtWidgets.QComboBox(self.widget)
        self.selected_user_script_combo_box.setMaxVisibleItems(40)
        self.selected_user_script_combo_box.setObjectName("selected_user_script_combo_box")
        self.verticalLayout.addWidget(self.selected_user_script_combo_box)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.user_script_params_text_field = QtWidgets.QTextEdit(self.widget)
        self.user_script_params_text_field.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_script_params_text_field.sizePolicy().hasHeightForWidth())
        self.user_script_params_text_field.setSizePolicy(sizePolicy)
        self.user_script_params_text_field.setMaximumSize(QtCore.QSize(200, 50))
        self.user_script_params_text_field.setObjectName("user_script_params_text_field")
        self.horizontalLayout_4.addWidget(self.user_script_params_text_field)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_rco_button = QtWidgets.QPushButton(self.widget)
        self.add_rco_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.add_rco_button.setObjectName("add_rco_button")
        self.horizontalLayout_5.addWidget(self.add_rco_button)
        self.evaluate_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evaluate_button.sizePolicy().hasHeightForWidth())
        self.evaluate_button.setSizePolicy(sizePolicy)
        self.evaluate_button.setObjectName("evaluate_button")
        self.horizontalLayout_5.addWidget(self.evaluate_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_to_queue_button = QtWidgets.QPushButton(self.widget)
        self.add_to_queue_button.setObjectName("add_to_queue_button")
        self.horizontalLayout_6.addWidget(self.add_to_queue_button)
        self.write_standard_awg_sequences_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_standard_awg_sequences_button.sizePolicy().hasHeightForWidth())
        self.write_standard_awg_sequences_button.setSizePolicy(sizePolicy)
        self.write_standard_awg_sequences_button.setObjectName("write_standard_awg_sequences_button")
        self.horizontalLayout_6.addWidget(self.write_standard_awg_sequences_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.script_queue_table = QTableWidgetEnhancedDrop(self.widget)
        self.script_queue_table.setEnabled(True)
        self.script_queue_table.setAutoFillBackground(False)
        self.script_queue_table.setFrameShape(QtWidgets.QFrame.Panel)
        self.script_queue_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.script_queue_table.setObjectName("script_queue_table")
        self.script_queue_table.setColumnCount(0)
        self.script_queue_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.script_queue_table)
        self.remove_next_script_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_next_script_button.sizePolicy().hasHeightForWidth())
        self.remove_next_script_button.setSizePolicy(sizePolicy)
        self.remove_next_script_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.remove_next_script_button.setObjectName("remove_next_script_button")
        self.verticalLayout_3.addWidget(self.remove_next_script_button)
        self.set_stop_request_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_stop_request_button.sizePolicy().hasHeightForWidth())
        self.set_stop_request_button.setSizePolicy(sizePolicy)
        self.set_stop_request_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.set_stop_request_button.setObjectName("set_stop_request_button")
        self.verticalLayout_3.addWidget(self.set_stop_request_button)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Form"))
        self.add_rco_button.setText(_translate("window", "Add refocus_confocal_odmr"))
        self.evaluate_button.setText(_translate("window", "run script evaluate"))
        self.add_to_queue_button.setText(_translate("window", "Add Script"))
        self.write_standard_awg_sequences_button.setText(_translate("window", "Write sequences"))
        self.remove_next_script_button.setText(_translate("window", "Remove next script"))
        self.set_stop_request_button.setText(_translate("window", "Set stop_request"))

from qutip_enhanced.qtgui.custom_widgets import QTableWidgetEnhancedDrop
